const Products = [
    {
      id: 1,
      name: "Apple iPhone 14",
      category: "celular",
      description: "Smartphone innovador con cámara avanzada.",
      image: "https://manofmany.com/wp-content/uploads/2022/09/iPhone-14-pro-Max-1200x900.jpg",
      price: "S/ 4,499",
    },
    {
      id: 2,
      name: "Samsung Galaxy S23",
      category: "celular",
      description: "Smartphone de alta gama con diseño moderno.",
      image: "https://www.androidauthority.com/wp-content/uploads/2023/01/samsung-galaxy-s23-lineup-standing.jpg",
      price: "S/ 3,999",
    },
    {
      id: 3,
      name: "Dell XPS 15",
      category: "laptop",
      description: "Laptop premium para profesionales creativos.",
      image: "https://cdn.mos.cms.futurecdn.net/5PxxHa4jXrwmGdKZpTWuZi-1200-80.jpg",
      price: "S/ 6,499",
    },
    {
      id: 4,
      name: "Apple MacBook Pro",
      category: "laptop",
      description: "Máxima potencia y rendimiento en un diseño elegante.",
      image: "https://www.bhphotovideo.com/images/images2500x2500/apple_mbp_14_sg_24_14_2_macbook_pro_with_1668224.jpg",
      price: "S/ 8,999",
    },
    {
      id: 5,
      name: "Sony Bravia 4K TV",
      category: "televisor",
      description: "Televisor 4K para una experiencia visual inigualable.",
      image: "https://www.worten.pt/i/5e71c13603c78c375656a572232eb1ee7a28ecb1.jpg",
      price: "S/ 5,999",
    },
    {
      id: 6,
      name: "LG OLED TV",
      category: "televisor",
      description: "Tecnología OLED para colores vibrantes y negros profundos.",
      image: "https://cdn.mos.cms.futurecdn.net/YkjkdYkHYMJ6Ju2CrRpvjA.jpg",
      price: "S/ 7,299",
    },
    {
      id: 7,
      name: "Sony WH-1000XM4",
      category: "audifonos",
      description: "Audifonos de alta calidad con tecnología de alto rendimiento.",
      image: "https://images.idgesg.net/images/article/2020/09/5j0a0247_final-100857111-orig.jpg",
      price: "S/ 2,999",
    },
    {
      id: 8,
      name: "Apple iPhone 15 Pro",
      category: "celular",
      description: "El último iPhone con pantalla ProMotion y cámara mejorada.",
      image: "https://th.bing.com/th/id/OIP.i5PqoQaSLhvBTT8qbtxAfAHaHa?rs=1&pid=ImgDetMain",
      price: "S/ 5,499",
    },
    {
      id: 9,
      name: "Samsung Galaxy Z Fold 5",
      category: "celular",
      description: "Smartphone plegable con pantalla dinámica y multitarea avanzada.",
      image: "https://th.bing.com/th/id/R.fe2b1efe50443a18da5f3f3411826e45?rik=J9M6qQPIsTacNw&pid=ImgRaw&r=0",
      price: "S/ 6,999",
    },
    {
      id: 10,
      name: "HP Spectre x360 2025",
      category: "laptop",
      description: "Laptop convertible con pantalla OLED y procesador de última generación.",
      image: "https://th.bing.com/th/id/R.75964f098f36ff25d4e402528a54a5ae?rik=swjiMhfJ%2bT4v6A&pid=ImgRaw&r=0",
      price: "S/ 7,999",
    },
    {
      id: 11,
      name: "Lenovo ThinkPad X1 Carbon Gen 10",
      category: "laptop",
      description: "Laptop ultraligera con duración de batería extendida y seguridad avanzada.",
      image: "https://notebookspec.com/web/wp-content/uploads/2022/05/Lenovo-ThinkPad-X1-Carbon_NYX02445-780x519.jpg",
      price: "S/ 8,499",
    },
    {
      id: 12,
      name: "Sony Bravia 8K TV 2024",
      category: "televisor",
      description: "Televisor 8K con tecnología Cognitive Processor XR para una experiencia visual inmersiva.",
      image: "https://coolboxpe.vtexassets.com/arquivos/ids/379962-1600-1600?v=638588409390370000&width=1600&height=1600&aspect=true",
      price: "S/ 12,999",
    },
    {
      id: 13,
      name: "LG G3 OLED TV 2025",
      category: "televisor",
      description: "Televisor OLED con brillo mejorado y diseño sin bordes.",
      image: "https://www.lg.com/us/images/tvs/md08003937/gallery/DZ02.jpg",
      price: "S/ 9,999",
    },
    {
      id: 14,
      name: "Bose QuietComfort Ultra 2024",
      category: "audifonos",
      description: "Audífonos con cancelación de ruido líder en la industria y sonido envolvente.",
      image: "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/QCUH-HEADPHONEARN/product_silo_images/AEM_PDP_GALLERY_BLACK-6.png/jcr:content/renditions/cq5dam.web.1920.1920.png",
      price: "S/ 3,499",
    },
    {
      id: 15,
      name: "Sony WF-1000XM5",
      category: "audifonos",
      description: "Audífonos inalámbricos con cancelación de ruido y calidad de sonido excepcional.",
      image: "https://www.soundandvision.com/images/styles/600_wide/public/072423_SV_1000XM5.jpg",
      price: "S/ 2,799",
    },
    {
      id: 16,
      name: "Google Pixel 8 Pro",
      category: "celular",
      description: "Smartphone con IA avanzada y cámara de fotografía computacional.",
      image: "https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2023/10/google-pixel-8-pro-3191842.jpg?tf=828x",
      price: "S/ 4,999",
    },
    {
      id: 17,
      name: "OnePlus 12",
      category: "celular",
      description: "Smartphone con pantalla Fluid AMOLED y carga rápida de 100W.",
      image: "https://www.androidheadlines.com/wp-content/uploads/2023/01/OnePlus-11-Review-AM-AH-26.jpg",
      price: "S/ 4,299",
    },
    {
      id: 18,
      name: "Asus ROG Zephyrus G15 2025",
      category: "laptop",
      description: "Laptop gaming con tarjeta gráfica NVIDIA RTX 4080 y pantalla QHD.",
      image: "https://th.bing.com/th/id/R.682c38852e79c0140fb4658dd34b4900?rik=Yu5Mk%2bQ%2b3m0puA&pid=ImgRaw&r=0",
      price: "S/ 9,999",
    },
    {
      id: 19,
      name: "Microsoft Surface Laptop 6",
      category: "laptop",
      description: "Laptop elegante con pantalla táctil y procesador Intel Core i7 de 13ª generación.",
      image: "https://surfacestore.com.vn/wp-content/uploads/2023/07/surface-laptop-6-4.jpg",
      price: "S/ 7,499",
    },
    {
      id: 20,
      name: "Samsung QN900C Neo QLED 8K TV",
      category: "televisor",
      description: "Televisor 8K con tecnología Neo QLED y diseño Infinity Screen.",
      image: "https://static1.pocketlintimages.com/wordpress/wp-content/uploads/2023/04/samsung-qn900c.jpg",
      price: "S/ 14,999",
    },
  ];
  
  export default Products;